export interface Articulo {
  slug: string
  categoria: string
  titulo: string
  extracto: string
  autor: string
  fecha: string
  lectura: string
  imagen: string
  metaDescription: string
  contenido: SeccionContenido[]
  faqs?: { pregunta: string; respuesta: string }[]
  enlaces?: { texto: string; href: string }[]
}

export interface SeccionContenido {
  tipo: 'h2' | 'h3' | 'p' | 'ul' | 'ol' | 'destacado' | 'toc'
  texto?: string
  items?: string[]
}

export const articulos: Articulo[] = [
  {
    slug: 'inquiocupacion-como-evitarla-propietario',
    categoria: 'Legal y fiscal',
    titulo: 'Inquiocupación: qué es, cómo ocurre y cómo evitarla como propietario',
    extracto: 'La inquiocupación es hoy el mayor miedo de los propietarios que quieren poner su piso en alquiler. En este artículo explicamos qué es exactamente, por qué es tan difícil de revertir y qué medidas reales existen para evitarla antes de que ocurra.',
    autor: 'Equipo Renttia',
    fecha: '12 jul 2026',
    lectura: '9 min',
    imagen: 'https://images.unsplash.com/photo-1560440021-33f9b867899d?w=800&q=80',
    metaDescription: 'Qué es la inquiocupación, cómo ocurre y cómo protegerse como propietario. Descubre las medidas preventivas reales para evitar que ocupen tu piso en alquiler.',
    contenido: [
      { tipo: 'p', texto: 'En los últimos años, el término "inquiocupación" ha entrado con fuerza en el vocabulario de cualquier propietario que se plantea poner su vivienda en alquiler. Y con razón: se trata de una de las situaciones legales más complejas, costosas y emocionalmente agotadoras a las que puede enfrentarse alguien que simplemente quiere obtener una renta mensual de su inmueble.' },
      { tipo: 'h2', texto: '¿Qué es exactamente la inquiocupación?' },
      { tipo: 'p', texto: 'La inquiocupación es la situación en la que un inquilino que entró legalmente en la vivienda —con contrato firmado y todo en regla— deja de pagar la renta pero se niega a abandonar el inmueble. A diferencia de la ocupación ilegal, aquí la persona entró con permiso del propietario. Eso lo complica todo.' },
      { tipo: 'p', texto: 'El inquiocupante aprovecha los largos plazos del proceso judicial de desahucio en España para permanecer meses o incluso años en la vivienda sin pagar. Durante todo ese tiempo, el propietario no cobra, pero sigue asumiendo los gastos fijos del inmueble.' },
      { tipo: 'h2', texto: '¿Por qué es tan difícil recuperar la vivienda?' },
      { tipo: 'p', texto: 'El sistema judicial español, aunque ha mejorado con reformas recientes, sigue siendo lento. Un proceso de desahucio puede tardar entre 6 meses y 2 años dependiendo de la comunidad autónoma, la saturación de los juzgados y si el inquilino solicita medidas de suspensión por vulnerabilidad.' },
      { tipo: 'ul', items: [
        'El propietario debe contratar abogado y procurador para iniciar el proceso',
        'Si el inquilino alega vulnerabilidad, los servicios sociales pueden pedir una prórroga de hasta 2 años adicionales',
        'El coste total (honorarios legales, mensajes sin cobrar, gastos de comunidad) puede superar los 15.000€',
        'Durante todo el proceso, la vivienda no puede arrendarse a nadie más',
      ]},
      { tipo: 'h2', texto: '¿Cuántos propietarios afecta en España?' },
      { tipo: 'p', texto: 'Según datos del Consejo General del Poder Judicial, en 2024 se presentaron más de 40.000 demandas de desahucio por impago en España. Aragón y La Rioja no son ajenas a esta tendencia, aunque con cifras proporcionalmente menores que Madrid o Barcelona. Pero estadística aparte, la percepción del riesgo entre los propietarios es muy alta: muchos prefieren dejar el piso vacío antes que arriesgarse.' },
      { tipo: 'h2', texto: 'Medidas preventivas reales: lo que funciona y lo que no' },
      { tipo: 'h3', texto: 'El seguro de impago: útil pero con límites' },
      { tipo: 'p', texto: 'El seguro de impago es la medida más extendida. Cubre el alquiler durante un máximo de 12 meses (según la póliza) y los gastos legales del desahucio. Sin embargo, tiene limitaciones importantes: exige un scoring previo del inquilino que muchos perfiles legítimos no superan, y no elimina el tiempo ni el desgaste emocional del proceso.' },
      { tipo: 'h3', texto: 'El aval bancario' },
      { tipo: 'p', texto: 'Pedir uno o dos meses de aval bancario al inquilino da cierta cobertura económica, pero no resuelve el problema de fondo: si el inquilino no paga y no abandona, el proceso judicial sigue siendo igual de largo.' },
      { tipo: 'h3', texto: 'La selección rigurosa del inquilino' },
      { tipo: 'p', texto: 'Verificar nóminas, contrato laboral, historial de morosidad y referencias de anteriores arrendadores reduce significativamente el riesgo. Es la medida preventiva más eficaz que existe. El problema es que no está al alcance de todos los propietarios en términos de tiempo y conocimiento.' },
      { tipo: 'h2', texto: 'La solución de raíz: no alquilar a particulares' },
      { tipo: 'p', texto: 'La forma más efectiva de eliminar el riesgo de inquiocupación es que tu inquilino no sea una persona física, sino una empresa. Cuando el arrendatario es una empresa con responsabilidad jurídica, los mecanismos de reclamación son completamente distintos: más ágiles, más seguros y con mucha menor probabilidad de situaciones de impago prolongado.' },
      { tipo: 'destacado', texto: 'En Renttia, somos nosotros —como empresa— los que firmamos el contrato de arrendamiento con el propietario. Esto significa que el inquilino en tu contrato es una empresa, no una persona física. La inquiocupación, tal y como existe en el alquiler tradicional, desaparece.' },
      { tipo: 'h2', texto: 'Conclusión: el riesgo existe pero tiene solución' },
      { tipo: 'p', texto: 'La inquiocupación es un riesgo real pero no inevitable. Los propietarios que conocen bien el mercado y utilizan las herramientas adecuadas pueden alquilar con tranquilidad. La clave está en elegir bien a quién alquilas y bajo qué estructura legal.' },
    ],
  },
  {
    slug: 'rent-to-rent-que-es-beneficios-propietario',
    categoria: 'Guías para propietarios',
    titulo: 'Rent to Rent: qué es y por qué puede ser la mejor decisión para tu piso',
    extracto: 'El modelo Rent to Rent está cambiando la forma en que los propietarios alquilan sus inmuebles en España. En esta guía explicamos en qué consiste, cómo funciona exactamente y por qué cada vez más propietarios en Zaragoza, Logroño y Huesca eligen esta alternativa.',
    autor: 'Equipo Renttia',
    fecha: '5 jul 2026',
    lectura: '8 min',
    imagen: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80',
    metaDescription: 'Qué es el modelo Rent to Rent, cómo funciona y por qué beneficia a los propietarios que quieren cobrar su alquiler sin complicaciones. Guía completa 2026.',
    contenido: [
      { tipo: 'p', texto: 'El modelo Rent to Rent (RTR) lleva años funcionando con éxito en el Reino Unido y otros países europeos. En España ha ido ganando terreno en los últimos años y está transformando la manera en que muchos propietarios gestionan —o más bien, dejan de gestionar— sus inmuebles.' },
      { tipo: 'h2', texto: '¿Qué significa exactamente Rent to Rent?' },
      { tipo: 'p', texto: 'Rent to Rent significa, literalmente, alquilar para volver a alquilar. En este modelo, una empresa —el operador RTR— alquila el inmueble al propietario mediante un contrato formal, y luego gestiona ese inmueble alquilando las habitaciones individualmente a distintos residentes.' },
      { tipo: 'p', texto: 'Para el propietario, la experiencia es idéntica a la de un alquiler tradicional, con una diferencia fundamental: su inquilino es una empresa, no un particular.' },
      { tipo: 'h2', texto: '¿Cómo funciona paso a paso?' },
      { tipo: 'ol', items: [
        'El propietario y la empresa RTR firman un contrato de arrendamiento de uso distinto a vivienda',
        'La empresa asume los suministros, el mantenimiento y la gestión integral del inmueble',
        'En muchos casos, la empresa realiza una reforma o acondicionamiento antes de entrar',
        'El propietario cobra su renta puntualmente cada mes, sin intervenir en nada más',
        'Al finalizar el contrato, el inmueble se devuelve en iguales o mejores condiciones',
      ]},
      { tipo: 'h2', texto: '¿Qué ventajas tiene para el propietario?' },
      { tipo: 'h3', texto: 'Renta garantizada sin dependencia del inquilino' },
      { tipo: 'p', texto: 'El propietario cobra su renta aunque el inmueble esté parcialmente vacío o haya problemas con algún residente. Eso es problema del operador RTR, no del propietario. Este es el punto que más valoran los propietarios que han sufrido impagos en el pasado.' },
      { tipo: 'h3', texto: 'Cero gestión' },
      { tipo: 'p', texto: 'Nada de llamadas por averías, nada de negociar con inquilinos, nada de renovar contratos. El propietario tiene un único interlocutor —la empresa— y ese interlocutor se encarga de absolutamente todo.' },
      { tipo: 'h3', texto: 'Inmueble en mejor estado' },
      { tipo: 'p', texto: 'Los operadores RTR profesionales tienen incentivo económico para mantener el inmueble en perfecto estado: un piso bien cuidado se alquila mejor y más rápido. Es habitual que al inicio del contrato se realice una reforma o lavado de cara que mejora el valor del inmueble a largo plazo.' },
      { tipo: 'h3', texto: 'Estabilidad contractual' },
      { tipo: 'p', texto: 'Los contratos de arrendamiento de uso distinto a vivienda tienen una duración más larga que los contratos residenciales estándar. Esto elimina la rotación constante de inquilinos y la incertidumbre asociada.' },
      { tipo: 'h2', texto: '¿Qué dice la ley sobre el Rent to Rent en España?' },
      { tipo: 'p', texto: 'El modelo RTR opera bajo la figura del contrato de arrendamiento de uso distinto a vivienda, regulado por el artículo 3 de la Ley de Arrendamientos Urbanos (LAU). Este tipo de contrato está pensado precisamente para usos que no son exclusivamente residenciales, como los pisos compartidos gestionados profesionalmente.' },
      { tipo: 'p', texto: 'Es un contrato completamente legal, frecuente y bien documentado en la jurisprudencia española. La clave está en que la empresa que firma es el arrendatario y los residentes son sub-arrendatarios o convivientes bajo la responsabilidad del operador, no del propietario.' },
      { tipo: 'destacado', texto: 'En Renttia operamos con contratos de arrendamiento de uso distinto a vivienda revisados por asesoría jurídica. El propietario tiene un único contrato, un único interlocutor y una única transferencia al mes.' },
      { tipo: 'h2', texto: '¿Para qué tipo de propietario funciona mejor el RTR?' },
      { tipo: 'p', texto: 'El modelo RTR es especialmente adecuado para propietarios que tienen un piso de 3 o más habitaciones, que no quieren dedicar tiempo a la gestión y que buscan cobrar su renta de forma fiable cada mes. También es ideal para quienes han tenido malas experiencias con inquilinos en el pasado y buscan una alternativa más segura.' },
    ],
  },
  {
    slug: 'impagos-alquiler-coste-real-propietario',
    categoria: 'Legal y fiscal',
    titulo: 'Impagos en el alquiler: el coste real que muy pocos propietarios calculan',
    extracto: 'Cuando un inquilino deja de pagar, el coste para el propietario va mucho más allá de los meses sin cobrar. Honorarios legales, gastos de comunidad, suministros y el tiempo perdido se acumulan hasta cifras que sorprenden. Analizamos el impacto real.',
    autor: 'Equipo Renttia',
    fecha: '28 jun 2026',
    lectura: '7 min',
    imagen: 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=800&q=80',
    metaDescription: 'Cuánto cuesta realmente un impago de alquiler: meses sin cobrar, honorarios legales, gastos fijos y el coste emocional. Análisis completo para propietarios.',
    contenido: [
      { tipo: 'p', texto: 'El primer mes sin cobrar siempre sorprende. El propietario piensa que será algo puntual, que el inquilino pondrá al día la deuda en pocos días. Pero cuando empieza el proceso de impago, la espiral de costes puede volverse imparable. Este artículo analiza, con números reales, cuánto puede llegar a costar un impago de alquiler en España.' },
      { tipo: 'h2', texto: 'La primera capa de pérdidas: las rentas sin cobrar' },
      { tipo: 'p', texto: 'El caso más habitual es un proceso de desahucio que dura entre 8 y 14 meses. Si la renta es de 800€/mes, el propietario deja de ingresar entre 6.400€ y 11.200€ solo en rentas. Pero eso es solo el principio.' },
      { tipo: 'h2', texto: 'La segunda capa: los gastos que siguen corriendo' },
      { tipo: 'p', texto: 'Aunque el inquilino no pague, el propietario sigue teniendo obligaciones económicas sobre el inmueble. Dependiendo de lo que esté contratado a nombre del propietario:' },
      { tipo: 'ul', items: [
        'Gastos de comunidad: entre 50€ y 150€/mes según el edificio',
        'IBI: proporcional al periodo de impago',
        'Seguro del hogar: si está a nombre del propietario',
        'Hipoteca (si existe): no para ni un solo mes',
      ]},
      { tipo: 'h2', texto: 'La tercera capa: los costes legales' },
      { tipo: 'p', texto: 'Iniciar un proceso de desahucio en España requiere contratar a un abogado y a un procurador. Los costes orientativos son:' },
      { tipo: 'ul', items: [
        'Abogado: entre 800€ y 2.500€ dependiendo de la complejidad y duración',
        'Procurador: entre 200€ y 600€',
        'Tasas judiciales: generalmente exentas para personas físicas, pero existen para empresas',
        'Cerrajero para el lanzamiento: entre 100€ y 300€',
      ]},
      { tipo: 'destacado', texto: 'El coste total de un impago de alquiler en España, incluyendo rentas no cobradas, gastos fijos y costes legales, puede superar los 20.000€ en casos donde el proceso se prolonga más de un año.' },
      { tipo: 'h2', texto: 'El coste que no aparece en ninguna factura: el desgaste emocional' },
      { tipo: 'p', texto: 'La dimensión emocional del impago es real y tiene consecuencias prácticas. Los propietarios que pasan por un proceso de desahucio describen meses de ansiedad, noches sin dormir y una sensación de impotencia ante un sistema que perciben como injusto. Muchos de ellos deciden no volver a alquilar nunca más, perdiendo así la rentabilidad de su inmueble durante años.' },
      { tipo: 'h2', texto: '¿Cómo calcular tu exposición al riesgo?' },
      { tipo: 'p', texto: 'Una fórmula sencilla para estimar tu exposición máxima al riesgo: (Renta mensual × 14) + 3.000€ en gastos legales y administrativos. Ese es el coste que deberías estar dispuesto a asumir antes de alquilar a un particular sin protección adicional.' },
      { tipo: 'h2', texto: 'La alternativa: eliminar el riesgo de raíz' },
      { tipo: 'p', texto: 'La única forma de eliminar completamente el riesgo de impago es que tu inquilino sea una empresa con responsabilidad económica verificable. Cuando una empresa es tu arrendataria, los mecanismos de reclamación son más ágiles y la probabilidad de impago sostenido es estadísticamente mucho menor.' },
      { tipo: 'p', texto: 'Además, una empresa operadora de coliving tiene un incentivo económico directo para mantenerte pagado: si no paga al propietario, pierde el acceso al inmueble y con él toda su actividad. Esa alineación de intereses es la mejor garantía que existe.' },
    ],
  },
  {
    slug: 'contrato-arrendamiento-uso-distinto-vivienda-propietarios',
    categoria: 'Legal y fiscal',
    titulo: 'Contrato de arrendamiento de uso distinto a vivienda: la protección que no sabías que necesitabas',
    extracto: 'El contrato de arrendamiento de uso distinto a vivienda es la figura jurídica que utilizan los operadores de coliving y Rent to Rent en España. Explicamos qué lo diferencia del contrato residencial tradicional y qué ventajas reales ofrece al propietario.',
    autor: 'Equipo Renttia',
    fecha: '20 jun 2026',
    lectura: '6 min',
    imagen: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&q=80',
    metaDescription: 'Qué es el contrato de arrendamiento de uso distinto a vivienda, en qué se diferencia del contrato residencial y por qué protege mejor al propietario que alquila a una empresa.',
    contenido: [
      { tipo: 'p', texto: 'Cuando un propietario firma un contrato de alquiler estándar con un particular, está sujeto a las limitaciones y plazos que establece la Ley de Arrendamientos Urbanos para los contratos de uso de vivienda. Sin embargo, existe otra figura contractual, completamente legal y cada vez más utilizada, que ofrece condiciones más favorables para el propietario: el contrato de arrendamiento de uso distinto a vivienda.' },
      { tipo: 'h2', texto: '¿Qué dice la ley?' },
      { tipo: 'p', texto: 'El artículo 3 de la Ley de Arrendamientos Urbanos (LAU) define el arrendamiento para uso distinto al de vivienda como aquel que recae sobre una edificación habitable cuyo destino primordial sea diferente al de satisfacer la necesidad permanente de vivienda del arrendatario. Este tipo de contrato se rige principalmente por la voluntad de las partes y, supletoriamente, por el Código Civil.' },
      { tipo: 'h2', texto: '¿En qué se diferencia del contrato residencial?' },
      { tipo: 'ul', items: [
        'No hay plazo mínimo obligatorio de 5 años para el propietario como en el contrato residencial',
        'La duración del contrato la pactan libremente las partes',
        'No aplica la prórroga obligatoria de 3 años adicionales del artículo 10 LAU',
        'El proceso de desahucio es más ágil que en el contrato residencial',
        'No existe el derecho de tanteo y retracto del arrendatario en caso de venta',
      ]},
      { tipo: 'h2', texto: '¿Cuándo se utiliza este tipo de contrato?' },
      { tipo: 'p', texto: 'Se utiliza cuando el arrendatario no va a utilizar el inmueble como su residencia habitual y permanente. Es el caso habitual de los operadores de coliving y Rent to Rent: la empresa arrienda el inmueble para gestionarlo como piso compartido, no para vivir en él.' },
      { tipo: 'h3', texto: 'Ejemplos de uso legítimo' },
      { tipo: 'ul', items: [
        'Empresas de coliving que gestionan pisos compartidos profesionalmente',
        'Operadores de alojamiento temporal (estudiantes, trabajadores en movilidad)',
        'Empresas que alquilan pisos para alojar a sus empleados',
        'Inmuebles destinados a uso mixto (residencial y profesional)',
      ]},
      { tipo: 'h2', texto: 'Ventajas concretas para el propietario' },
      { tipo: 'h3', texto: 'Mayor control sobre el inmueble' },
      { tipo: 'p', texto: 'Con un contrato de uso distinto a vivienda, el propietario recupera antes el inmueble si surgen incumplimientos. El proceso judicial es más ágil y predecible que en el desahucio de un contrato residencial.' },
      { tipo: 'h3', texto: 'Condiciones pactadas libremente' },
      { tipo: 'p', texto: 'Desde la duración hasta las condiciones de mantenimiento, reforma o entrega, todo puede pactarse con mayor libertad. Esto permite diseñar un contrato que se adapte exactamente a la situación del inmueble y a las expectativas del propietario.' },
      { tipo: 'destacado', texto: 'En Renttia firmamos siempre contratos de arrendamiento de uso distinto a vivienda, revisados por nuestro asesor jurídico. El propietario recibe una copia completa antes de la firma y dispone del tiempo que necesite para revisarlo con su propio abogado si lo desea.' },
      { tipo: 'h2', texto: '¿Tiene algún riesgo para el propietario?' },
      { tipo: 'p', texto: 'Como todo contrato, debe estar bien redactado y recoger con claridad las obligaciones de ambas partes: qué se entrega, en qué estado, qué puede modificarse en el inmueble, cómo se gestiona el mantenimiento y cómo se resuelve el contrato. Un contrato bien hecho protege a ambas partes y evita conflictos.' },
    ],
  },
  // ── NUEVOS ARTÍCULOS SEO ─────────────────────────────────────────────────
  {
    slug: 'trucos-para-echar-a-un-inquilino-que-no-paga',
    categoria: 'Legal y fiscal',
    titulo: 'Trucos para echar a un inquilino que no paga: pasos legales y estrategias reales',
    extracto: 'Cuando un inquilino deja de pagar, la mayoría de propietarios no sabe por dónde empezar. En este artículo explicamos los pasos legales reales, qué funciona, qué no, y cómo acortar al máximo el tiempo hasta recuperar tu vivienda.',
    autor: 'Equipo Renttia',
    fecha: '18 jul 2026',
    lectura: '10 min',
    imagen: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80',
    metaDescription: 'Trucos legales para echar a un inquilino que no paga: burofax, acuerdo extrajudicial, proceso de desahucio y cómo acelerar los plazos. Guía completa 2026.',
    contenido: [
      { tipo: 'p', texto: 'Cada año, miles de propietarios en España se enfrentan a la misma situación: el inquilino deja de pagar y no se va. El proceso puede durar meses o incluso años si no se gestiona bien desde el primer momento. Aquí tienes los pasos reales, en orden, para actuar de forma efectiva.' },
      { tipo: 'toc' },
      { tipo: 'h2', texto: 'Lo primero que debes hacer cuando el inquilino no paga' },
      { tipo: 'p', texto: 'En el momento en que se cumple el primer mes sin cobrar, debes actuar. No esperes un segundo mes pensando que se arreglará solo. El tiempo juega en tu contra: cada día que pasa sin actuar es un día más de deuda y un día más que el proceso se alarga.' },
      { tipo: 'ul', items: [
        'Documenta el impago: guarda el justificante bancario que demuestra que no hubo ingreso',
        'Contacta primero de forma informal: a veces es un error bancario o un problema puntual resoluble',
        'Si no hay respuesta en 48-72 horas, da el siguiente paso sin más dilación',
      ]},
      { tipo: 'h2', texto: 'El burofax: el paso más importante y más ignorado' },
      { tipo: 'p', texto: 'El burofax es el documento que acredita de forma fehaciente que has reclamado la deuda al inquilino. Sin burofax, el proceso judicial es más complicado. Con burofax, tienes una prueba irrefutable de que el inquilino recibió tu reclamación y no respondió.' },
      { tipo: 'p', texto: 'El burofax debe incluir: el importe de la deuda, la fecha desde la que no se ha pagado, un requerimiento expreso para que abone la deuda o abandone el inmueble, y un plazo razonable para hacerlo (generalmente 10-15 días).' },
      { tipo: 'destacado', texto: 'Envía el burofax con acuse de recibo y certificación de contenido. El coste es de unos 15-30€ en cualquier oficina de Correos. Es el gasto más rentable que puedes hacer en este proceso.' },
      { tipo: 'h2', texto: 'El acuerdo extrajudicial: el truco que más funciona' },
      { tipo: 'p', texto: 'Antes de ir al juzgado, considera proponer un acuerdo extrajudicial al inquilino. En muchos casos, el inquilino sabe que perderá el proceso judicial y prefiere llegar a un acuerdo: por ejemplo, marcharse en 30 días a cambio de que no le reclames parte de la deuda o le des tiempo para encontrar otro piso.' },
      { tipo: 'p', texto: 'Este acuerdo debe formalizarse siempre por escrito, ante notario o mediante un acta notarial de entrega de llaves. Un acuerdo verbal no tiene valor legal suficiente.' },
      { tipo: 'h2', texto: 'Proceso de desahucio por impago: paso a paso' },
      { tipo: 'ol', items: [
        'Envío del burofax reclamando la deuda (mes 1)',
        'Si no hay respuesta, contratación de abogado y procurador',
        'Presentación de la demanda de desahucio por falta de pago ante el juzgado',
        'Notificación al inquilino: tiene 10 días para pagar y quedarse, pagar e irse, o negarse',
        'Si se niega, se fija fecha de juicio y, si procede, de lanzamiento (desalojo físico)',
        'El día del lanzamiento, el juzgado procede al desalojo con la presencia del secretario judicial',
      ]},
      { tipo: 'h2', texto: '¿Cuánto tiempo tarda el desahucio por impago?' },
      { tipo: 'p', texto: 'En España, la duración media de un proceso de desahucio por impago oscila entre 6 y 18 meses, dependiendo de la comunidad autónoma y la carga del juzgado. Aragón (Zaragoza y Huesca) tiene tiempos relativamente más cortos que la media nacional: entre 5 y 9 meses si el proceso va sin complicaciones.' },
      { tipo: 'h2', texto: 'Lo que NO debes hacer bajo ningún concepto' },
      { tipo: 'ul', items: [
        'No cambies la cerradura mientras el inquilino sigue en la vivienda: es delito de coacciones',
        'No cortes los suministros de agua o luz: también puede ser constitutivo de delito',
        'No entres en la vivienda sin permiso del inquilino o autorización judicial',
        'No aceptes pagos parciales sin dejar constancia escrita de que no implican condonación del resto de la deuda',
        'No amenaces ni presiones al inquilino fuera de los canales legales',
      ]},
      { tipo: 'h2', texto: '¿Y si el inquilino alega vulnerabilidad?' },
      { tipo: 'p', texto: 'La Ley de Vivienda de 2023 introdujo mecanismos de suspensión del desahucio cuando el inquilino acredita situación de vulnerabilidad ante los servicios sociales. En ese caso, el juzgado puede suspender el lanzamiento hasta que los servicios sociales ofrezcan una alternativa habitacional, con un plazo máximo que varía según si el arrendador es gran tenedor o no.' },
      { tipo: 'p', texto: 'Si eres un propietario particular (pequeño tenedor), el plazo máximo de suspensión es de 2 meses. Si eres considerado gran tenedor (10 o más inmuebles), puede ser de hasta 4 meses.' },
      { tipo: 'h2', texto: 'Cómo evitar que esto vuelva a ocurrir' },
      { tipo: 'p', texto: 'La mejor estrategia es preventiva. Alquilar a una empresa en lugar de a un particular elimina de raíz el riesgo de este tipo de situaciones. Cuando tu inquilino es una empresa, el contrato es mercantil, los plazos de respuesta son más cortos y la probabilidad de impago sostenido es estadísticamente mucho menor.' },
      { tipo: 'destacado', texto: 'En Renttia somos nosotros, como empresa, quienes firmamos el contrato con el propietario. Si hay un problema con algún residente, es nuestro problema, no el tuyo. Tú sigues cobrando el día 1 de cada mes.' },
    ],
    faqs: [
      { pregunta: '¿Cuánto tarda en España un desahucio por impago?', respuesta: 'Entre 6 y 18 meses de media, dependiendo de la comunidad autónoma. En Aragón, los tiempos suelen estar entre 5 y 9 meses si no hay complicaciones.' },
      { pregunta: '¿Es obligatorio enviar burofax antes del desahucio?', respuesta: 'No es estrictamente obligatorio, pero es muy recomendable. El burofax acredita fehacientemente la reclamación y refuerza enormemente la posición del propietario en el proceso judicial.' },
      { pregunta: '¿Puedo cambiar la cerradura si el inquilino no paga?', respuesta: 'No. Cambiar la cerradura mientras el inquilino sigue en la vivienda es un delito de coacciones que puede volverse en tu contra. Solo se puede hacer tras el lanzamiento judicial.' },
      { pregunta: '¿Qué pasa si el inquilino paga solo parte de la deuda?', respuesta: 'Si paga parte, el desahucio puede continuar si sigue debiendo. Documenta cualquier pago parcial y deja claro por escrito que no implica renuncia al resto de la deuda.' },
    ],
    enlaces: [
      { texto: 'Cómo echar a un inquiokupa: proceso completo y plazos reales', href: '/blog/como-echar-a-un-inquiokupa' },
      { texto: 'Nueva ley para echar inquilinos: qué ha cambiado en 2026', href: '/blog/nueva-ley-para-echar-inquilinos' },
      { texto: 'Impagos en el alquiler: el coste real que nadie te cuenta', href: '/blog/impagos-alquiler-coste-real-propietario' },
      { texto: 'Inquiocupación: qué es y cómo evitarla como propietario', href: '/blog/inquiocupacion-como-evitarla-propietario' },
    ],
  },
  {
    slug: 'se-puede-echar-a-un-inquilino-por-necesitar-el-piso',
    categoria: 'Legal y fiscal',
    titulo: '¿Se puede echar a un inquilino por necesitar el piso? La causa de necesidad en la LAU',
    extracto: 'Sí, la ley permite recuperar tu vivienda alquilada si la necesitas para ti o un familiar. Pero tiene condiciones, plazos y consecuencias si no se cumplen. Te explicamos todo lo que necesitas saber sobre la causa de necesidad en la Ley de Arrendamientos Urbanos.',
    autor: 'Equipo Renttia',
    fecha: '17 jul 2026',
    lectura: '8 min',
    imagen: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80',
    metaDescription: '¿Se puede echar a un inquilino por necesitar el piso? Sí, con la causa de necesidad del artículo 9.3 LAU. Requisitos, plazos, preaviso y consecuencias. Guía 2026.',
    contenido: [
      { tipo: 'p', texto: 'Una de las preguntas más frecuentes entre los propietarios que tienen un piso alquilado es si pueden recuperarlo cuando lo necesitan para uso propio o de un familiar. La respuesta es sí, pero con condiciones muy específicas que conviene conocer bien antes de actuar.' },
      { tipo: 'toc' },
      { tipo: 'h2', texto: 'Qué dice la ley: el artículo 9.3 de la LAU' },
      { tipo: 'p', texto: 'El artículo 9.3 de la Ley de Arrendamientos Urbanos establece que, una vez transcurrido el primer año de contrato, el arrendador podrá no renovar el contrato alegando necesidad de la vivienda para sí mismo, su cónyuge en los supuestos de separación o divorcio, o sus familiares en primer grado de consanguinidad o por adopción, o para su cónyuge en los supuestos de sentencia firme de divorcio o nulidad matrimonial.' },
      { tipo: 'p', texto: 'Esta cláusula debe estar recogida expresamente en el contrato de arrendamiento. Si el contrato no menciona la posibilidad de causa de necesidad, el propietario no puede invocarla.' },
      { tipo: 'h2', texto: 'Requisitos para alegar causa de necesidad' },
      { tipo: 'ul', items: [
        'El contrato de arrendamiento debe incluir expresamente la cláusula de causa de necesidad',
        'Debe haber transcurrido al menos el primer año del contrato',
        'La necesidad debe ser para el propio arrendador, su cónyuge (en caso de divorcio) o familiar de primer grado',
        'El aviso debe darse con al menos 2 meses de antelación',
        'La necesidad debe ser real: si se demuestra que era ficticia, hay consecuencias graves',
      ]},
      { tipo: 'h2', texto: 'El plazo de preaviso: cuánto tiempo antes hay que avisar' },
      { tipo: 'p', texto: 'El propietario debe comunicar al inquilino su intención de recuperar la vivienda con un mínimo de 2 meses de antelación. Esta comunicación debe hacerse de forma fehaciente —burofax o notificación notarial— para que quede constancia legal.' },
      { tipo: 'p', texto: 'Una vez comunicada, el inquilino tiene derecho a permanecer en la vivienda durante esos 2 meses. Pasado ese plazo, si no la abandona voluntariamente, el propietario deberá acudir al juzgado.' },
      { tipo: 'h2', texto: 'Qué pasa si el propietario no ocupa el piso tras el desalojo' },
      { tipo: 'p', texto: 'Si en el plazo de 3 meses desde el desalojo el propietario o familiar no ocupa la vivienda, el inquilino tiene derecho a recuperarla, y si no puede hacerlo, a recibir una indemnización equivalente a una mensualidad de renta por cada año de contrato que faltaba por cumplir (con un mínimo de 3 mensualidades).' },
      { tipo: 'destacado', texto: 'La causa de necesidad ficticia tiene consecuencias económicas serias. Si invocas esta causa sin necesidad real, el ex-inquilino puede reclamarte una indemnización importante y hay sentencias que la han concedido incluso con daños y perjuicios adicionales.' },
      { tipo: 'h2', texto: 'Casos en los que NO funciona la causa de necesidad' },
      { tipo: 'ul', items: [
        'Si el contrato no incluye expresamente la cláusula de causa de necesidad',
        'Si el familiar que va a ocupar la vivienda no es de primer grado (no vale para primos, tíos, sobrinos)',
        'Si ya han pasado los 5 años de contrato y el inquilino está en la prórroga legal de 3 años adicionales',
        'Si la notificación no se hizo con al menos 2 meses de antelación',
      ]},
      { tipo: 'h2', texto: 'La Ley de Vivienda 2023 y la causa de necesidad' },
      { tipo: 'p', texto: 'La Ley 12/2023 de Vivienda no eliminó la causa de necesidad, pero introdujo mayor protección para los inquilinos en zonas tensionadas. En estas zonas, el propietario debe acreditar aún con más rigor que la necesidad es real y verificable. En Zaragoza y Huesca no hay actualmente zonas declaradas formalmente como tensionadas, por lo que la causa de necesidad opera según la LAU estándar.' },
      { tipo: 'h2', texto: 'Alternativa: el modelo que evita estos dilemas' },
      { tipo: 'p', texto: 'Si firmas con una empresa operadora en lugar de con un particular, el contrato es de uso distinto a vivienda y no aplica la prórroga obligatoria de la LAU residencial. Esto significa que cuando necesitas tu piso, puedes recuperarlo al vencimiento del contrato sin necesidad de alegar causa alguna, con el preaviso pactado.' },
    ],
    faqs: [
      { pregunta: '¿Con cuánto tiempo de aviso debo notificar la causa de necesidad?', respuesta: 'Con un mínimo de 2 meses de antelación, mediante comunicación fehaciente (burofax o notificación notarial).' },
      { pregunta: '¿Puedo usar la causa de necesidad para mis padres?', respuesta: 'Sí. Los padres son familiares de primer grado de consanguinidad, por lo que están incluidos en el artículo 9.3 de la LAU.' },
      { pregunta: '¿Qué pasa si el inquilino no se va tras la notificación?', respuesta: 'Deberás acudir al juzgado para solicitar el desahucio por expiración del plazo contractual. El proceso es diferente al desahucio por impago y suele resolverse más rápidamente.' },
      { pregunta: '¿Tengo que devolver la fianza si uso la causa de necesidad?', respuesta: 'Sí. Al finalizar el contrato, tienes la obligación de devolver la fianza en el plazo legal (generalmente 1 mes desde la entrega de llaves) salvo que haya desperfectos imputables al inquilino.' },
    ],
    enlaces: [
      { texto: 'Prórroga del contrato de alquiler: plazos y cómo evitarla', href: '/blog/prorroga-contrato-alquiler' },
      { texto: 'Nueva ley para echar inquilinos: qué cambió en 2026', href: '/blog/nueva-ley-para-echar-inquilinos' },
      { texto: 'Trucos para echar a un inquilino que no paga', href: '/blog/trucos-para-echar-a-un-inquilino-que-no-paga' },
    ],
  },
  {
    slug: 'nueva-ley-para-echar-inquilinos',
    categoria: 'Legal y fiscal',
    titulo: 'Nueva ley para echar inquilinos: qué ha cambiado y qué sigue igual en 2026',
    extracto: 'La Ley de Vivienda de 2023 generó mucha incertidumbre entre los propietarios sobre sus derechos para recuperar la vivienda. En este artículo analizamos qué cambió realmente respecto al desahucio, qué sigue igual y cómo afecta al propietario medio en ciudades como Zaragoza o Huesca.',
    autor: 'Equipo Renttia',
    fecha: '16 jul 2026',
    lectura: '9 min',
    imagen: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&q=80',
    metaDescription: 'Nueva ley para echar inquilinos en 2026: qué cambió con la Ley de Vivienda 2023, plazos de desahucio, suspensiones por vulnerabilidad y derechos del propietario.',
    contenido: [
      { tipo: 'p', texto: 'Desde la aprobación de la Ley 12/2023 de Vivienda, muchos propietarios tienen la sensación de que sus derechos se han reducido drásticamente. Algunos afirman que "ya no se puede echar a un inquilino". La realidad es más matizada: hay cambios importantes, pero el derecho del propietario a recuperar su vivienda sigue existiendo.' },
      { tipo: 'toc' },
      { tipo: 'h2', texto: 'Qué cambió con la Ley de Vivienda de 2023' },
      { tipo: 'p', texto: 'La Ley 12/2023, conocida como Ley de Vivienda, introdujo varios cambios en el marco del alquiler residencial en España. Los más relevantes para los propietarios que quieren recuperar su vivienda son:' },
      { tipo: 'ul', items: [
        'Mayor protección para inquilinos en situación de vulnerabilidad: el juzgado puede suspender el desahucio hasta que los servicios sociales ofrezcan alternativa habitacional',
        'Diferente trato para grandes tenedores (10+ inmuebles) y pequeños propietarios',
        'Introducción de zonas de mercado residencial tensionado, donde el propietario tiene obligaciones adicionales',
        'Refuerzo del concepto de "gran tenedor" en zonas tensionadas: basta con 5 inmuebles en esa zona',
      ]},
      { tipo: 'h2', texto: 'Qué NO cambió: el derecho a recuperar la vivienda' },
      { tipo: 'p', texto: 'El proceso de desahucio por impago sigue existiendo. La causa de necesidad sigue siendo válida. La expiración del contrato sigue siendo motivo para pedir la vivienda. Lo que cambió es que hay más mecanismos de suspensión temporal y más trámites cuando el inquilino alega vulnerabilidad.' },
      { tipo: 'h2', texto: 'El mecanismo de suspensión por vulnerabilidad: cómo funciona' },
      { tipo: 'p', texto: 'Cuando se inicia un proceso de desahucio, el juzgado debe notificar a los servicios sociales municipales. Si el inquilino acredita situación de vulnerabilidad, los servicios sociales tienen un plazo para emitir un informe y, en su caso, ofrecer una alternativa habitacional.' },
      { tipo: 'p', texto: 'Durante este proceso, el lanzamiento puede suspenderse. El plazo máximo de suspensión para pequeños propietarios (menos de 10 inmuebles) es de 2 meses. Para grandes tenedores, es de 4 meses.' },
      { tipo: 'destacado', texto: 'Si eres un propietario particular con uno o pocos pisos, la suspensión máxima es de 2 meses. No indefinida, no de años. Dos meses. El proceso sigue adelante pasado ese plazo.' },
      { tipo: 'h2', texto: 'Los plazos reales del desahucio en 2026' },
      { tipo: 'p', texto: 'Con la nueva ley, el proceso completo puede tardar algo más que antes en casos de vulnerabilidad, pero sigue siendo finito. En términos medios para un propietario particular (pequeño tenedor) en una ciudad como Zaragoza o Huesca:' },
      { tipo: 'ul', items: [
        'Desde el primer impago hasta la demanda: 1-2 meses',
        'Desde la demanda hasta el juicio: 3-6 meses',
        'Proceso de vulnerabilidad (si aplica): hasta 2 meses adicionales',
        'Desde el juicio hasta el lanzamiento: 1-2 meses',
        'Total estimado: 6 a 12 meses en la mayoría de casos',
      ]},
      { tipo: 'h2', texto: 'Cómo afecta la ley según el tipo de propietario' },
      { tipo: 'h3', texto: 'Pequeño propietario (menos de 10 inmuebles)' },
      { tipo: 'p', texto: 'Tiene un tratamiento más favorable en casi todos los aspectos: suspensión máxima de 2 meses, menor exposición a las restricciones de zonas tensionadas y la causa de necesidad sigue funcionando igual.' },
      { tipo: 'h3', texto: 'Gran tenedor (10 o más inmuebles, o 5 en zona tensionada)' },
      { tipo: 'p', texto: 'Tiene obligaciones adicionales: suspensión de hasta 4 meses, obligación de ofrecer alternativa habitacional a inquilinos vulnerables antes del desahucio en zonas tensionadas, y restricciones en la subida de rentas.' },
      { tipo: 'h2', texto: 'Lo que los propietarios pueden hacer ahora mismo' },
      { tipo: 'p', texto: 'La nueva ley no elimina las opciones del propietario, pero refuerza la importancia de contratar bien desde el principio: buenos contratos, buena selección de inquilinos y, si es posible, arrendar a una empresa en lugar de a un particular para estar fuera del ámbito de la LAU residencial.' },
    ],
    faqs: [
      { pregunta: '¿La nueva ley de vivienda impide echar a un inquilino?', respuesta: 'No. El derecho a recuperar la vivienda por impago o expiración de contrato sigue vigente. La ley añade mecanismos de suspensión temporal (máximo 2-4 meses) en casos de vulnerabilidad.' },
      { pregunta: '¿Qué es un gran tenedor según la nueva ley?', respuesta: 'Un propietario con 10 o más inmuebles de uso residencial, o con 5 o más en una zona de mercado tensionado. Los grandes tenedores tienen obligaciones adicionales.' },
      { pregunta: '¿Zaragoza o Huesca son zonas tensionadas?', respuesta: 'Actualmente no hay zonas declaradas formalmente como tensionadas en Aragón. La declaración corresponde a las comunidades autónomas, y Aragón no ha realizado esta declaración.' },
      { pregunta: '¿Puedo alquilar a una empresa para evitar la nueva ley?', respuesta: 'Sí. El contrato de arrendamiento de uso distinto a vivienda (con una empresa como arrendataria) no está sujeto a la LAU residencial ni a las restricciones de la Ley de Vivienda 2023.' },
    ],
    enlaces: [
      { texto: 'Ley de Vivienda y alquiler: guía completa para propietarios', href: '/blog/ley-de-vivienda-alquiler' },
      { texto: 'Prórroga del contrato de alquiler: cuándo aplica y cómo evitarla', href: '/blog/prorroga-contrato-alquiler' },
      { texto: 'Trucos para echar a un inquilino que no paga', href: '/blog/trucos-para-echar-a-un-inquilino-que-no-paga' },
      { texto: 'Contrato de arrendamiento de uso distinto a vivienda: la protección que no sabías que necesitabas', href: '/blog/contrato-arrendamiento-uso-distinto-vivienda-propietarios' },
    ],
  },
  {
    slug: 'ley-de-vivienda-alquiler',
    categoria: 'Legal y fiscal',
    titulo: 'Ley de Vivienda y alquiler: todo lo que debe saber el propietario en 2026',
    extracto: 'La Ley 12/2023 de Vivienda cambió las reglas del alquiler en España. Zonas tensionadas, límites a la renta, grandes tenedores, nuevos plazos y obligaciones para los propietarios. Explicamos todo de forma clara para que puedas tomar decisiones informadas.',
    autor: 'Equipo Renttia',
    fecha: '15 jul 2026',
    lectura: '8 min',
    imagen: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80',
    metaDescription: 'Ley de Vivienda y alquiler en 2026: zonas tensionadas, grandes tenedores, límites de renta, índices de actualización y derechos del propietario. Guía completa.',
    contenido: [
      { tipo: 'p', texto: 'La Ley 12/2023, de 24 de mayo, por el derecho a la vivienda, es la primera ley estatal de vivienda en España desde 1946. Su impacto en el mercado del alquiler ha sido significativo y sigue generando debate entre propietarios, inquilinos y expertos. Esta guía explica los puntos clave que afectan directamente a los propietarios que tienen o quieren poner un piso en alquiler.' },
      { tipo: 'toc' },
      { tipo: 'h2', texto: 'Qué es la Ley de Vivienda y cuándo entró en vigor' },
      { tipo: 'p', texto: 'La Ley 12/2023 de Vivienda entró en vigor el 26 de mayo de 2023. Modifica, entre otras normas, la LAU (Ley de Arrendamientos Urbanos) y la Ley de Propiedad Horizontal. Su objetivo declarado es garantizar el acceso a la vivienda, especialmente en zonas con mayor presión sobre los precios del alquiler.' },
      { tipo: 'h2', texto: 'Zonas de mercado residencial tensionado: qué son y cómo afectan' },
      { tipo: 'p', texto: 'La ley permite a las comunidades autónomas declarar determinadas zonas como "mercado residencial tensionado". Para ello, deben acreditar que el precio del alquiler ha subido más de un 3% por encima del IPC en los últimos 5 años, o que el esfuerzo económico de las familias para pagar el alquiler supera el 30% de sus ingresos.' },
      { tipo: 'p', texto: 'En estas zonas, los propietarios tienen limitaciones adicionales en la actualización de la renta y, si son grandes tenedores, en el precio de nuevos contratos. Actualmente, Cataluña es la única comunidad que ha aplicado estas declaraciones de forma extensiva. Aragón no ha declarado ninguna zona tensionada.' },
      { tipo: 'h2', texto: 'El nuevo índice de actualización de la renta' },
      { tipo: 'p', texto: 'Hasta 2023, la renta podía actualizarse según el IPC, lo que en 2022 supuso subidas de hasta el 10%. La Ley de Vivienda estableció un límite transitorio: en 2023 máximo el 2%, en 2024 máximo el 3%. A partir de 2025, aplica un nuevo índice específico elaborado por el INE, generalmente por debajo del IPC general.' },
      { tipo: 'destacado', texto: 'El nuevo índice de actualización de rentas del INE es más moderado que el IPC. Para los propietarios, esto significa que las actualizaciones anuales de la renta están limitadas a un porcentaje más bajo que la inflación general.' },
      { tipo: 'h2', texto: 'Grandes tenedores: quiénes son y qué obligaciones tienen' },
      { tipo: 'ul', items: [
        'Fuera de zonas tensionadas: quienes tienen 10 o más inmuebles de uso residencial',
        'En zonas tensionadas: quienes tienen 5 o más inmuebles en esa zona',
        'Obligación de informar sobre la condición de gran tenedor al firmar nuevos contratos',
        'En zonas tensionadas: obligación de ofrecer alternativa habitacional antes del desahucio en casos de vulnerabilidad',
        'Posible limitación del precio del alquiler al índice de referencia en zonas tensionadas',
      ]},
      { tipo: 'h2', texto: 'Cambios en los plazos de los contratos de alquiler' },
      { tipo: 'p', texto: 'La Ley de Vivienda no modificó los plazos básicos de la LAU: siguen siendo 5 años de duración mínima para el arrendador (7 si es persona jurídica) y 3 años de prórroga obligatoria posterior. Lo que sí reforzó es la protección frente al desahucio durante estos plazos.' },
      { tipo: 'h2', texto: 'Nuevas obligaciones al inicio del contrato' },
      { tipo: 'ul', items: [
        'El propietario debe informar al inquilino si es gran tenedor',
        'En zonas tensionadas, debe informar sobre el precio de referencia aplicable',
        'Los gastos de gestión inmobiliaria y los honorarios de la agencia son obligación del arrendador, no del inquilino',
        'El propietario debe facilitar copia del contrato al inquilino firmada por ambas partes',
      ]},
      { tipo: 'h2', texto: 'Cómo afecta al contrato de arrendamiento de uso distinto a vivienda' },
      { tipo: 'p', texto: 'El contrato de arrendamiento de uso distinto a vivienda (el utilizado por empresas como Renttia para operar pisos compartidos) no está sujeto a la LAU residencial ni a las restricciones de la Ley de Vivienda 2023. La duración, la renta y las condiciones son de libre pacto entre las partes. Este es uno de los motivos por los que muchos propietarios con pisos de 3 o más habitaciones optan por este modelo.' },
    ],
    faqs: [
      { pregunta: '¿La Ley de Vivienda limita cuánto puedo cobrar de alquiler?', respuesta: 'Solo en zonas declaradas tensionadas, y con condiciones según si eres gran tenedor o no. En ciudades como Zaragoza o Huesca, donde no hay zonas tensionadas, puedes pactar libremente la renta.' },
      { pregunta: '¿Quién paga los honorarios de la inmobiliaria con la nueva ley?', respuesta: 'El propietario, siempre. La Ley de Vivienda estableció que los gastos de gestión inmobiliaria y honorarios de agencia son obligación del arrendador, no del inquilino.' },
      { pregunta: '¿Puedo subir el alquiler a mi inquilino actual?', respuesta: 'Solo según el índice de actualización pactado en el contrato, y dentro del límite del índice del INE vigente (o el IPC si es más favorable). La subida arbitraria unilateral no está permitida.' },
      { pregunta: '¿Afecta la Ley de Vivienda a los pisos alquilados a empresas?', respuesta: 'No. Los contratos de arrendamiento de uso distinto a vivienda (empresa como arrendataria) no están bajo el ámbito de la LAU residencial ni de la Ley de Vivienda 2023.' },
    ],
    enlaces: [
      { texto: 'Nueva ley para echar inquilinos: qué cambió y qué sigue igual', href: '/blog/nueva-ley-para-echar-inquilinos' },
      { texto: 'Prórroga del contrato de alquiler: plazos y cómo evitarla', href: '/blog/prorroga-contrato-alquiler' },
      { texto: 'Contrato de arrendamiento de uso distinto a vivienda', href: '/blog/contrato-arrendamiento-uso-distinto-vivienda-propietarios' },
    ],
  },
  {
    slug: 'prorroga-contrato-alquiler',
    categoria: 'Legal y fiscal',
    titulo: 'Prórroga del contrato de alquiler: cuándo aplica, cómo evitarla y qué dice la ley',
    extracto: 'La prórroga automática del contrato de alquiler es uno de los puntos que más confusión genera entre propietarios. ¿Cuántos años debe quedar el inquilino si no quiere irse? ¿Cuándo puedo yo poner fin al contrato? ¿Qué pasa si no digo nada? Lo explicamos todo.',
    autor: 'Equipo Renttia',
    fecha: '14 jul 2026',
    lectura: '7 min',
    imagen: 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=800&q=80',
    metaDescription: 'Prórroga contrato alquiler en 2026: plazos legales, cuándo aplica la prórroga obligatoria, tácita reconducción y cómo evitar que el inquilino permanezca más de lo deseado.',
    contenido: [
      { tipo: 'p', texto: 'La prórroga del contrato de alquiler es la extensión automática del contrato una vez que ha llegado a su fecha de vencimiento. En España, la LAU establece un sistema de prórrogas obligatorias que protege al inquilino y obliga al propietario a mantener el contrato más allá del plazo inicialmente pactado, salvo excepciones.' },
      { tipo: 'toc' },
      { tipo: 'h2', texto: 'Cuánto dura el contrato de alquiler por ley' },
      { tipo: 'p', texto: 'La LAU distingue según quién es el arrendador:' },
      { tipo: 'ul', items: [
        'Arrendador persona física (particular): duración mínima de 5 años',
        'Arrendador persona jurídica (empresa): duración mínima de 7 años',
        'Contratos firmados por tiempo inferior a 5/7 años se prorrogan automáticamente hasta alcanzar ese mínimo',
      ]},
      { tipo: 'h2', texto: 'La prórroga obligatoria: los 3 años adicionales' },
      { tipo: 'p', texto: 'Una vez cumplidos los 5 años (o 7 si el arrendador es empresa), si ninguna de las partes notifica su intención de no renovar, el contrato se prorroga por plazos anuales hasta un máximo de 3 años adicionales. Esta prórroga también es obligatoria para el propietario, salvo que comunique su voluntad de no renovar con 4 meses de antelación.' },
      { tipo: 'p', texto: 'El inquilino, en cambio, puede abandonar la vivienda durante la prórroga con solo 2 meses de preaviso.' },
      { tipo: 'destacado', texto: 'En total, un inquilino puede permanecer legalmente en tu piso hasta 8 años (5 + 3) si es un arrendador particular, o hasta 10 años (7 + 3) si el arrendador es una empresa, si no se hace nada.' },
      { tipo: 'h2', texto: 'Cómo evitar la prórroga como propietario' },
      { tipo: 'p', texto: 'Para no quedar atrapado en la prórroga, el propietario debe comunicar su voluntad de no renovar con al menos 4 meses de antelación al vencimiento del contrato. Esta comunicación debe ser fehaciente (burofax o notificación notarial). Si no se hace en plazo, el contrato se prorroga automáticamente por un año más.' },
      { tipo: 'h2', texto: 'La tácita reconducción: el peligro de la inactividad' },
      { tipo: 'p', texto: 'Si al terminar el periodo de prórroga obligatoria (los 3 años) ninguna de las partes hace nada, el contrato puede entrar en "tácita reconducción". En este caso, el contrato se renueva por periodos muy cortos (días o meses) pero el régimen legal cambia: ya no aplica la LAU sino el Código Civil, lo que tiene implicaciones específicas.' },
      { tipo: 'p', texto: 'Para evitar la tácita reconducción, el propietario debe comunicar formalmente, antes del fin de la prórroga, que el contrato no se renovará.' },
      { tipo: 'h2', texto: 'Cuándo puede el propietario finalizar el contrato antes de tiempo' },
      { tipo: 'ul', items: [
        'Impago de la renta o de cualquier cantidad cuyo pago haya asumido el inquilino',
        'Subarriendo o cesión sin consentimiento del propietario',
        'Realización de obras no autorizadas que causen daños en la vivienda',
        'Actividades molestas, insalubres, nocivas, peligrosas o ilícitas',
        'Causa de necesidad del propietario (si está pactada en el contrato)',
      ]},
      { tipo: 'h2', texto: 'El contrato de uso distinto a vivienda: sin prórrogas obligatorias' },
      { tipo: 'p', texto: 'Si el arrendatario es una empresa (no un particular que usará la vivienda como residencia habitual), el contrato es de uso distinto a vivienda y se rige por la voluntad de las partes. Esto significa que la duración, la prórroga y las condiciones de terminación las pactan libremente propietario y empresa. No hay prórroga obligatoria de 5 años ni los 3 años adicionales. Al vencimiento, el contrato termina si ninguna de las partes quiere renovarlo.' },
    ],
    faqs: [
      { pregunta: '¿Con cuánto tiempo debo avisar para no renovar el contrato?', respuesta: 'Con al menos 4 meses de antelación si eres el propietario, y 2 meses si eres el inquilino. La comunicación debe ser fehaciente (burofax o notificación notarial).' },
      { pregunta: '¿Puede el inquilino quedarse 8 años en mi piso?', respuesta: 'Sí, si es un propietario particular: 5 años de contrato mínimo más 3 años de prórroga obligatoria. Para evitarlo, debes comunicar la no renovación con 4 meses de antelación al final del contrato.' },
      { pregunta: '¿Qué pasa si no digo nada al vencer el contrato?', respuesta: 'El contrato se prorroga automáticamente por un año más (si estás en la fase de prórroga obligatoria). Si ya se cumplieron los 8 años totales y nadie dice nada, puede entrar en tácita reconducción.' },
      { pregunta: '¿El inquilino puede irse antes de que acabe el contrato?', respuesta: 'Sí, a partir del 6º mes puede desistir del contrato con 2 meses de preaviso. Antes del 6º mes, podría tener que indemnizar al propietario con una mensualidad por año restante.' },
    ],
    enlaces: [
      { texto: 'Ley de Vivienda y alquiler: todo lo que necesitas saber en 2026', href: '/blog/ley-de-vivienda-alquiler' },
      { texto: '¿Se puede echar a un inquilino por necesitar el piso?', href: '/blog/se-puede-echar-a-un-inquilino-por-necesitar-el-piso' },
      { texto: 'Rent to Rent: qué es y por qué beneficia al propietario', href: '/blog/rent-to-rent-que-es-beneficios-propietario' },
    ],
  },
  {
    slug: 'piso-en-herencia-que-hacer',
    categoria: 'Gestión inmobiliaria',
    titulo: 'Piso en herencia: qué hacer, opciones reales y cómo sacarle rentabilidad',
    extracto: 'Heredar un piso puede ser una oportunidad o una carga, dependiendo de cómo se gestione. Impuestos, decisiones sobre qué hacer con él, opciones para rentabilizarlo y errores frecuentes que conviene evitar. Guía práctica para herederos de inmuebles en 2026.',
    autor: 'Equipo Renttia',
    fecha: '13 jul 2026',
    lectura: '9 min',
    imagen: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80',
    metaDescription: 'Qué hacer con un piso en herencia en 2026: aceptar o renunciar, impuestos, trámites, vender, alquilar o gestionar. Guía completa para herederos de inmuebles.',
    contenido: [
      { tipo: 'p', texto: 'Heredar un piso es, para muchas familias, una mezcla de alivio económico y complejidad emocional y administrativa. El piso existe, hay que hacer algo con él, y las opciones no siempre están claras. Esta guía responde a las preguntas más frecuentes que nos hacen propietarios que han heredado una vivienda y no saben por dónde empezar.' },
      { tipo: 'toc' },
      { tipo: 'h2', texto: 'Lo primero: aceptar o renunciar la herencia' },
      { tipo: 'p', texto: 'Antes de hacer nada con el piso, hay que aceptar la herencia. Esto parece obvio, pero tiene implicaciones: al aceptar la herencia, aceptas también las deudas del fallecido. Si el piso tiene hipoteca pendiente, derramas atrasadas o deudas con la comunidad, pasas a ser responsable de ellas.' },
      { tipo: 'p', texto: 'Existe la opción de "aceptar a beneficio de inventario", que limita tu responsabilidad al valor de lo heredado. Si hay dudas sobre posibles deudas ocultas, es la opción más prudente. Tienes 30 años para aceptar o renunciar, pero conviene actuar con relativa rapidez para evitar gastos de comunidad, IBI y otros costes que siguen generándose.' },
      { tipo: 'h2', texto: 'Los impuestos que debes pagar al heredar un piso' },
      { tipo: 'ul', items: [
        'Impuesto de Sucesiones y Donaciones: varía enormemente por comunidad autónoma. En Aragón hay reducciones importantes para herencias entre familiares directos',
        'Plusvalía municipal (IIVTNU): impuesto municipal sobre el incremento del valor del terreno. Se paga al Ayuntamiento del municipio donde está el piso',
        'IRPF: si vendes el piso heredado, tributarás por la ganancia patrimonial en la declaración de la renta',
      ]},
      { tipo: 'destacado', texto: 'En Aragón, las herencias entre padres e hijos tienen una reducción del 100% en el Impuesto de Sucesiones hasta 500.000€ por heredero, con bonificación del 65% en el resto. Consulta con un asesor fiscal antes de actuar.' },
      { tipo: 'h2', texto: 'Trámites para heredar el piso correctamente' },
      { tipo: 'ol', items: [
        'Obtener el certificado de defunción del fallecido',
        'Acudir al Registro de Actos de Última Voluntad para saber si hay testamento',
        'Obtener el certificado de últimas voluntades',
        'Si hay testamento: escritura de aceptación de herencia ante notario',
        'Si no hay testamento: declaración de herederos ab intestato',
        'Inscribir el piso en el Registro de la Propiedad a nombre del heredero',
        'Liquidar el Impuesto de Sucesiones en la comunidad autónoma correspondiente',
      ]},
      { tipo: 'h2', texto: 'Opciones para gestionar el piso heredado' },
      { tipo: 'h3', texto: '1. Vender el piso' },
      { tipo: 'p', texto: 'Es la opción más simple si no quieres complicaciones a largo plazo. Permite obtener liquidez inmediata. El punto negativo: tributarás por la ganancia patrimonial en IRPF, y si el mercado no está en buen momento, puede que no sea el mejor momento para vender.' },
      { tipo: 'h3', texto: '2. Alquilar el piso de forma tradicional' },
      { tipo: 'p', texto: 'Si el piso es habitable y está bien ubicado, el alquiler genera una renta mensual estable. El riesgo principal es la gestión: selección de inquilinos, incidencias, impagos. Requiere tiempo y conocimiento o contratar una agencia.' },
      { tipo: 'h3', texto: '3. Ceder la gestión a una empresa operadora' },
      { tipo: 'p', texto: 'Si el piso tiene 3 o más habitaciones, puede encajar con el modelo de piso compartido gestionado profesionalmente. La empresa alquila el piso completo al propietario (renta garantizada), lo gestiona íntegramente y el propietario no tiene que ocuparse de nada. Es el modelo que más tranquilidad aporta a los herederos que no quieren ser "caseros".' },
      { tipo: 'h3', texto: '4. Usarlo como vivienda propia' },
      { tipo: 'p', texto: 'Si necesitas la vivienda para vivir, es la opción más directa. Recuerda que si la vendes después de haberla usado como residencia habitual durante al menos 3 años, la ganancia patrimonial puede estar exenta en IRPF.' },
      { tipo: 'h2', texto: 'Errores frecuentes al heredar un piso' },
      { tipo: 'ul', items: [
        'No liquidar el Impuesto de Sucesiones en plazo (6 meses desde el fallecimiento): genera intereses de demora',
        'No inscribir el piso en el Registro de la Propiedad: deja la propiedad en situación jurídica incierta',
        'Empezar a alquilarlo sin haber tramitado la herencia: genera problemas contractuales y fiscales',
        'Aceptar pura y simplemente sin verificar deudas: puedes heredar también deudas superiores al valor del piso',
        'No coordinar con los demás herederos si el piso es indiviso: puede bloquearse cualquier decisión',
      ]},
      { tipo: 'h2', texto: 'Si el piso está en Zaragoza o Huesca: qué puedes hacer' },
      { tipo: 'p', texto: 'Zaragoza y Huesca tienen una demanda estable de alquiler de habitaciones, especialmente en zonas universitarias y de servicios. Un piso heredado bien ubicado en estas ciudades puede convertirse en una fuente de ingresos muy sólida si se gestiona correctamente desde el principio.' },
    ],
    faqs: [
      { pregunta: '¿Cuánto tiempo tengo para liquidar el Impuesto de Sucesiones?', respuesta: '6 meses desde la fecha de fallecimiento. Se puede solicitar prórroga por otros 6 meses. Si se supera el plazo sin pagar, se generan intereses de demora y recargos.' },
      { pregunta: '¿Puedo alquilar el piso antes de terminar los trámites de la herencia?', respuesta: 'Técnicamente no, porque el piso no está aún a tu nombre. Es recomendable esperar a tener la escritura de aceptación de herencia firmada y el piso inscrito en el Registro.' },
      { pregunta: '¿Qué pasa si hay varios herederos y uno quiere vender y otro no?', respuesta: 'Si no hay acuerdo, cualquier heredero puede solicitar judicialmente la división de la cosa común (actio communi dividundo), lo que puede obligar a la venta pública del inmueble. La mejor solución es llegar a un acuerdo extrajudicial.' },
      { pregunta: '¿Puedo renunciar solo a parte de la herencia?', respuesta: 'No. La herencia es un todo: o se acepta completa o se renuncia completa. No puedes quedarte el piso y renunciar a las deudas.' },
    ],
    enlaces: [
      { texto: 'Cómo alquilar tu piso sin preocupaciones en 2026', href: '/blog/como-alquilar-piso-sin-preocupaciones-2026' },
      { texto: 'Rent to Rent: qué es y por qué puede ser la mejor decisión para tu piso heredado', href: '/blog/rent-to-rent-que-es-beneficios-propietario' },
      { texto: 'Ley de Vivienda y alquiler: lo que todo propietario debe saber', href: '/blog/ley-de-vivienda-alquiler' },
    ],
  },
  {
    slug: 'como-echar-a-un-inquiokupa',
    categoria: 'Legal y fiscal',
    titulo: 'Cómo echar a un inquiokupa: proceso legal, plazos reales y errores que debes evitar',
    extracto: 'El inquiokupa es el inquilino que entró legalmente pero dejó de pagar y no se va. Es una de las situaciones más complicadas del alquiler en España. Aquí tienes el proceso completo, los plazos reales y lo que NO debes hacer bajo ningún concepto.',
    autor: 'Equipo Renttia',
    fecha: '12 jul 2026',
    lectura: '9 min',
    imagen: 'https://images.unsplash.com/photo-1560440021-33f9b867899d?w=800&q=80',
    metaDescription: 'Cómo echar a un inquiokupa en 2026: diferencia con okupa, proceso de desahucio, plazos reales, vulnerabilidad y cómo protegerse antes de que ocurra.',
    contenido: [
      { tipo: 'p', texto: 'El término "inquiokupa" se ha popularizado en los últimos años para describir una figura muy específica y muy distinta de la ocupación ilegal: el inquilino que entró en la vivienda de forma completamente legal, con contrato firmado, pero que en algún momento dejó de pagar y se niega a abandonar el inmueble. Entender esta distinción es fundamental para saber cómo actuar.' },
      { tipo: 'toc' },
      { tipo: 'h2', texto: 'Inquiokupa vs okupa: una distinción fundamental' },
      { tipo: 'p', texto: 'La diferencia legal entre un inquiokupa y un okupa es enorme, y determina completamente el proceso a seguir:' },
      { tipo: 'ul', items: [
        'OKUPA: entró sin permiso, sin contrato, de forma ilegal. El proceso es penal (denuncia por allanamiento de morada o usurpación). Puede ser más rápido pero también más imprevisible.',
        'INQUIOKUPA: entró con contrato y con permiso del propietario. El proceso es civil (desahucio por impago). No hay denuncia penal posible por la entrada, solo por el impago.',
      ]},
      { tipo: 'h2', texto: 'Por qué el proceso con un inquiokupa es tan complicado' },
      { tipo: 'p', texto: 'El sistema judicial español protege al inquilino que entró legalmente mucho más que al okupa. Al haber un contrato de por medio, el propietario debe seguir el proceso civil de desahucio, que es más largo y formal. No puede simplemente pedir que la policía lo eche porque "no tiene derecho a estar ahí": jurídicamente, tiene un contrato que, aunque con impagos, le da cierta cobertura hasta que se resuelva judicialmente.' },
      { tipo: 'h2', texto: 'Proceso para echar a un inquiokupa paso a paso' },
      { tipo: 'ol', items: [
        'Mes 1 del impago: documentar el impago y contactar al inquilino',
        'Envío de burofax reclamando la deuda y advirtiendo de las consecuencias legales',
        'Si no paga ni se va: contratar abogado y procurador',
        'Presentar demanda de desahucio por impago en el juzgado de primera instancia',
        'El juzgado notifica al inquilino: tiene 10 días para pagar (enervación del desahucio), para irse o para oponerse',
        'Si se opone o no hace nada: juicio oral y posterior lanzamiento (desalojo físico)',
      ]},
      { tipo: 'h2', texto: 'Plazos reales del proceso en 2026' },
      { tipo: 'p', texto: 'La duración varía mucho según el juzgado y la comunidad autónoma. En Aragón, los juzgados tienen carga de trabajo moderada en comparación con Madrid o Barcelona. Estimación realista:' },
      { tipo: 'ul', items: [
        'Desde el primer impago hasta la demanda: 1-2 meses',
        'Desde la demanda hasta la notificación al inquilino: 2-4 semanas',
        'Desde la notificación hasta el juicio: 2-4 meses',
        'Si hay vulnerabilidad: suspensión adicional de hasta 2 meses (pequeño propietario)',
        'Desde el juicio hasta el lanzamiento: 2-6 semanas',
        'Total estimado en Aragón: 5 a 10 meses',
      ]},
      { tipo: 'h2', texto: 'El mecanismo de enervación: cómo el inquiokupa puede detener el proceso' },
      { tipo: 'p', texto: 'Una vez presentada la demanda, el inquilino puede enervar (frenar) el desahucio pagando toda la deuda acumulada hasta ese momento. Solo puede usar este mecanismo UNA VEZ durante todo el contrato. Si ya lo usó en el mismo contrato, la segunda vez no puede enervarlo aunque pague.' },
      { tipo: 'destacado', texto: 'Si el inquilino paga toda la deuda tras la demanda, el desahucio se para y el contrato continúa. Pero si deja de pagar de nuevo, ya no puede usar la enervación otra vez. En ese caso, el proceso es más rápido.' },
      { tipo: 'h2', texto: 'Lo que NO debes hacer al tratar con un inquiokupa' },
      { tipo: 'ul', items: [
        'No cambies la cerradura: es coacción, delito penal',
        'No cortes el agua, la luz o el gas: también es delito',
        'No entres en la vivienda sin permiso ni orden judicial',
        'No contrates a nadie para presionar o amedrentar al inquilino',
        'No aceptes pagos parciales sin dejar claro por escrito que no condonas el resto',
        'No amenaces ni acoses: puede volverse en tu contra en el proceso judicial',
      ]},
      { tipo: 'h2', texto: 'Cómo evitar tener un inquiokupa en el futuro' },
      { tipo: 'p', texto: 'La mejor protección es preventiva. Tres medidas concretas reducen drásticamente el riesgo:' },
      { tipo: 'ul', items: [
        'Selección rigurosa del inquilino: nóminas verificadas, contrato laboral estable, referencias',
        'Seguro de impago: cubre las rentas durante el proceso y los gastos legales',
        'Alquilar a una empresa: el arrendatario empresa tiene mecanismos de reclamación más ágiles y la probabilidad de impago sostenido es mucho menor',
      ]},
      { tipo: 'p', texto: 'Si tu piso tiene 3 o más habitaciones, el modelo de piso compartido gestionado por una empresa como Renttia elimina de raíz la figura del inquiokupa: el inquilino en tu contrato no es un particular, sino una empresa con responsabilidad jurídica y económica.' },
    ],
    faqs: [
      { pregunta: '¿Puedo llamar a la policía para que echen a un inquiokupa?', respuesta: 'No directamente. La policía no puede desalojar a alguien que entró legalmente con contrato. Debes seguir el proceso judicial de desahucio.' },
      { pregunta: '¿Qué diferencia hay entre inquiokupa y okupa?', respuesta: 'El okupa entró ilegalmente (sin permiso ni contrato), el proceso es penal. El inquiokupa entró con contrato y dejó de pagar, el proceso es civil (desahucio por impago). Son situaciones legalmente muy distintas.' },
      { pregunta: '¿Puedo recuperar el dinero que me debe el inquiokupa?', respuesta: 'Puedes incluir en la demanda tanto el desahucio como la reclamación de rentas impagadas. Pero cobrar lo que se debe puede ser complicado si el inquilino no tiene bienes embargables.' },
      { pregunta: '¿Cuánto cuesta el proceso de desahucio contra un inquiokupa?', respuesta: 'Entre 800€ y 2.500€ en honorarios de abogado y procurador, más tasas judiciales si aplican. Si tienes seguro de impago, estos costes suelen estar cubiertos.' },
    ],
    enlaces: [
      { texto: 'Trucos para echar a un inquilino que no paga: pasos legales', href: '/blog/trucos-para-echar-a-un-inquilino-que-no-paga' },
      { texto: 'Inquiocupación: qué es y cómo evitarla como propietario', href: '/blog/inquiocupacion-como-evitarla-propietario' },
      { texto: 'Nueva ley para echar inquilinos: qué ha cambiado en 2026', href: '/blog/nueva-ley-para-echar-inquilinos' },
      { texto: 'Impagos en el alquiler: el coste real que nadie calcula', href: '/blog/impagos-alquiler-coste-real-propietario' },
    ],
  },
  {
    slug: 'como-alquilar-piso-sin-preocupaciones-2026',
    categoria: 'Guías para propietarios',
    titulo: 'Cómo alquilar tu piso sin preocupaciones en 2026: guía práctica para propietarios',
    extracto: 'Alquilar una vivienda en España en 2026 implica más incertidumbre que nunca para los propietarios. En esta guía repasamos las opciones disponibles, sus ventajas e inconvenientes, y los pasos concretos para poner el piso en alquiler de forma segura.',
    autor: 'Equipo Renttia',
    fecha: '10 jun 2026',
    lectura: '10 min',
    imagen: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80',
    metaDescription: 'Guía práctica 2026 para propietarios que quieren alquilar su piso sin riesgos: opciones disponibles, cómo elegir inquilino, qué contratos usar y cómo cobrar siempre.',
    contenido: [
      { tipo: 'p', texto: 'El mercado del alquiler en España atraviesa un momento de alta tensión. La escasez de oferta en ciudades como Zaragoza, Logroño o Huesca convive con un clima de desconfianza entre propietarios que han visto o vivido situaciones de impago, ocupación o conflictos prolongados. Si tienes un piso y te planteas ponerlo en alquiler, esta guía te ayudará a tomar la decisión con información real.' },
      { tipo: 'h2', texto: 'El contexto del alquiler en 2026: qué ha cambiado' },
      { tipo: 'p', texto: 'La Ley de Vivienda de 2023 introdujo cambios relevantes en el mercado del alquiler residencial: limitaciones en zonas tensionadas, modificaciones en los plazos de los contratos y nuevas obligaciones para los grandes tenedores. Para los pequeños propietarios, el impacto más inmediato ha sido un aumento de la incertidumbre jurídica.' },
      { tipo: 'p', texto: 'A esto se suma una percepción generalizada de que el sistema judicial no protege suficientemente al propietario en casos de impago. El resultado: muchos pisos que podrían estar alquilados siguen vacíos porque sus propietarios no quieren arriesgarse.' },
      { tipo: 'h2', texto: 'Opciones para alquilar tu piso: ventajas e inconvenientes' },
      { tipo: 'h3', texto: '1. Alquiler tradicional gestionado por ti mismo' },
      { tipo: 'p', texto: 'Publicas el piso, recibes solicitudes, seleccionas al inquilino, firmas el contrato y gestionas todo lo que surja. Es la opción más común y la que más control da al propietario. También es la que más tiempo y conocimiento requiere, y la que expone más directamente al riesgo de impago.' },
      { tipo: 'h3', texto: '2. Gestión a través de una agencia inmobiliaria' },
      { tipo: 'p', texto: 'La agencia busca inquilino y cobra una comisión (generalmente una mensualidad). Después, la gestión diaria sigue siendo del propietario salvo que contrate un servicio adicional de administración. No elimina el riesgo de impago ni la gestión de incidencias.' },
      { tipo: 'h3', texto: '3. Alquiler con seguro de impago' },
      { tipo: 'p', texto: 'Añadir un seguro de impago (entre el 3% y el 5% de la renta anual) da cobertura durante un máximo de 12 meses y cubre los gastos legales del desahucio. Exige un scoring previo del inquilino. Reduce el riesgo económico pero no elimina el proceso ni el desgaste.' },
      { tipo: 'h3', texto: '4. Alquiler a una empresa (modelo Rent to Rent)' },
      { tipo: 'p', texto: 'El propietario alquila el inmueble a una empresa operadora que se convierte en su único inquilino. La empresa gestiona el inmueble, paga la renta puntualmente y devuelve el inmueble al final del contrato. Es el modelo que más se acerca a "alquilar sin preocupaciones".' },
      { tipo: 'h2', texto: 'Los cinco pasos para alquilar tu piso de forma segura' },
      { tipo: 'ol', items: [
        'Evalúa el estado del inmueble: ¿necesita reforma? ¿está habitable tal como está?',
        'Define tu objetivo: ¿quieres máxima rentabilidad o máxima tranquilidad? Las dos no siempre van juntas',
        'Decide el modelo de alquiler más adecuado para tu perfil y el del inmueble',
        'Prepara la documentación: cédula de habitabilidad, certificado energético, escrituras',
        'Elige bien a quién alquilas: no te precipites por llenar el piso rápido',
      ]},
      { tipo: 'h2', texto: 'Señales de alerta en la selección del inquilino' },
      { tipo: 'p', texto: 'Si optas por el alquiler tradicional, presta atención a estas señales que pueden indicar un perfil de riesgo elevado:' },
      { tipo: 'ul', items: [
        'Urgencia excesiva para firmar el contrato sin tiempo para revisar nada',
        'Nóminas o contratos laborales que no cuadran con el nivel de vida aparente',
        'Resistencia a proporcionar referencias de anteriores arrendadores',
        'Propuestas de pagar varios meses por adelantado sin justificación',
        'Interés en modificar cláusulas estándar del contrato relacionadas con las garantías',
      ]},
      { tipo: 'destacado', texto: 'Si tu piso tiene 3 o más habitaciones y está en Zaragoza, Logroño o Huesca, puedes pedir una valoración gratuita a Renttia. Te diremos si encaja con nuestro modelo y, si es así, te ofrecemos ser nosotros tu inquilino: con contrato, con renta garantizada y sin gestión para ti.' },
      { tipo: 'h2', texto: 'Conclusión: no hay una única respuesta, pero sí hay opciones mejores' },
      { tipo: 'p', texto: 'Alquilar en 2026 es perfectamente viable si se hace con información y con las herramientas adecuadas. El propietario que se protege bien puede obtener una renta estable y predecible de su inmueble durante años, sin sobresaltos. El que se lanza sin preparación asume unos riesgos que pueden costar muy caro.' },
    ],
  },
]
