export interface Articulo {
  slug: string
  categoria: string
  titulo: string
  extracto: string
  autor: string
  fecha: string
  lectura: string
  imagen: string
  metaDescription: string
  contenido: SeccionContenido[]
}

export interface SeccionContenido {
  tipo: 'h2' | 'h3' | 'p' | 'ul' | 'ol' | 'destacado'
  texto?: string
  items?: string[]
}

export const articulos: Articulo[] = [
  {
    slug: 'inquiocupacion-como-evitarla-propietario',
    categoria: 'Legal y fiscal',
    titulo: 'Inquiocupación: qué es, cómo ocurre y cómo evitarla como propietario',
    extracto: 'La inquiocupación es hoy el mayor miedo de los propietarios que quieren poner su piso en alquiler. En este artículo explicamos qué es exactamente, por qué es tan difícil de revertir y qué medidas reales existen para evitarla antes de que ocurra.',
    autor: 'Equipo Renttia',
    fecha: '12 jul 2026',
    lectura: '9 min',
    imagen: 'https://images.unsplash.com/photo-1560440021-33f9b867899d?w=800&q=80',
    metaDescription: 'Qué es la inquiocupación, cómo ocurre y cómo protegerse como propietario. Descubre las medidas preventivas reales para evitar que ocupen tu piso en alquiler.',
    contenido: [
      { tipo: 'p', texto: 'En los últimos años, el término "inquiocupación" ha entrado con fuerza en el vocabulario de cualquier propietario que se plantea poner su vivienda en alquiler. Y con razón: se trata de una de las situaciones legales más complejas, costosas y emocionalmente agotadoras a las que puede enfrentarse alguien que simplemente quiere obtener una renta mensual de su inmueble.' },
      { tipo: 'h2', texto: '¿Qué es exactamente la inquiocupación?' },
      { tipo: 'p', texto: 'La inquiocupación es la situación en la que un inquilino que entró legalmente en la vivienda —con contrato firmado y todo en regla— deja de pagar la renta pero se niega a abandonar el inmueble. A diferencia de la ocupación ilegal, aquí la persona entró con permiso del propietario. Eso lo complica todo.' },
      { tipo: 'p', texto: 'El inquiocupante aprovecha los largos plazos del proceso judicial de desahucio en España para permanecer meses o incluso años en la vivienda sin pagar. Durante todo ese tiempo, el propietario no cobra, pero sigue asumiendo los gastos fijos del inmueble.' },
      { tipo: 'h2', texto: '¿Por qué es tan difícil recuperar la vivienda?' },
      { tipo: 'p', texto: 'El sistema judicial español, aunque ha mejorado con reformas recientes, sigue siendo lento. Un proceso de desahucio puede tardar entre 6 meses y 2 años dependiendo de la comunidad autónoma, la saturación de los juzgados y si el inquilino solicita medidas de suspensión por vulnerabilidad.' },
      { tipo: 'ul', items: [
        'El propietario debe contratar abogado y procurador para iniciar el proceso',
        'Si el inquilino alega vulnerabilidad, los servicios sociales pueden pedir una prórroga de hasta 2 años adicionales',
        'El coste total (honorarios legales, mensajes sin cobrar, gastos de comunidad) puede superar los 15.000€',
        'Durante todo el proceso, la vivienda no puede arrendarse a nadie más',
      ]},
      { tipo: 'h2', texto: '¿Cuántos propietarios afecta en España?' },
      { tipo: 'p', texto: 'Según datos del Consejo General del Poder Judicial, en 2024 se presentaron más de 40.000 demandas de desahucio por impago en España. Aragón y La Rioja no son ajenas a esta tendencia, aunque con cifras proporcionalmente menores que Madrid o Barcelona. Pero estadística aparte, la percepción del riesgo entre los propietarios es muy alta: muchos prefieren dejar el piso vacío antes que arriesgarse.' },
      { tipo: 'h2', texto: 'Medidas preventivas reales: lo que funciona y lo que no' },
      { tipo: 'h3', texto: 'El seguro de impago: útil pero con límites' },
      { tipo: 'p', texto: 'El seguro de impago es la medida más extendida. Cubre el alquiler durante un máximo de 12 meses (según la póliza) y los gastos legales del desahucio. Sin embargo, tiene limitaciones importantes: exige un scoring previo del inquilino que muchos perfiles legítimos no superan, y no elimina el tiempo ni el desgaste emocional del proceso.' },
      { tipo: 'h3', texto: 'El aval bancario' },
      { tipo: 'p', texto: 'Pedir uno o dos meses de aval bancario al inquilino da cierta cobertura económica, pero no resuelve el problema de fondo: si el inquilino no paga y no abandona, el proceso judicial sigue siendo igual de largo.' },
      { tipo: 'h3', texto: 'La selección rigurosa del inquilino' },
      { tipo: 'p', texto: 'Verificar nóminas, contrato laboral, historial de morosidad y referencias de anteriores arrendadores reduce significativamente el riesgo. Es la medida preventiva más eficaz que existe. El problema es que no está al alcance de todos los propietarios en términos de tiempo y conocimiento.' },
      { tipo: 'h2', texto: 'La solución de raíz: no alquilar a particulares' },
      { tipo: 'p', texto: 'La forma más efectiva de eliminar el riesgo de inquiocupación es que tu inquilino no sea una persona física, sino una empresa. Cuando el arrendatario es una empresa con responsabilidad jurídica, los mecanismos de reclamación son completamente distintos: más ágiles, más seguros y con mucha menor probabilidad de situaciones de impago prolongado.' },
      { tipo: 'destacado', texto: 'En Renttia, somos nosotros —como empresa— los que firmamos el contrato de arrendamiento con el propietario. Esto significa que el inquilino en tu contrato es una empresa, no una persona física. La inquiocupación, tal y como existe en el alquiler tradicional, desaparece.' },
      { tipo: 'h2', texto: 'Conclusión: el riesgo existe pero tiene solución' },
      { tipo: 'p', texto: 'La inquiocupación es un riesgo real pero no inevitable. Los propietarios que conocen bien el mercado y utilizan las herramientas adecuadas pueden alquilar con tranquilidad. La clave está en elegir bien a quién alquilas y bajo qué estructura legal.' },
    ],
  },
  {
    slug: 'rent-to-rent-que-es-beneficios-propietario',
    categoria: 'Guías para propietarios',
    titulo: 'Rent to Rent: qué es y por qué puede ser la mejor decisión para tu piso',
    extracto: 'El modelo Rent to Rent está cambiando la forma en que los propietarios alquilan sus inmuebles en España. En esta guía explicamos en qué consiste, cómo funciona exactamente y por qué cada vez más propietarios en Zaragoza, Logroño y Huesca eligen esta alternativa.',
    autor: 'Equipo Renttia',
    fecha: '5 jul 2026',
    lectura: '8 min',
    imagen: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80',
    metaDescription: 'Qué es el modelo Rent to Rent, cómo funciona y por qué beneficia a los propietarios que quieren cobrar su alquiler sin complicaciones. Guía completa 2026.',
    contenido: [
      { tipo: 'p', texto: 'El modelo Rent to Rent (RTR) lleva años funcionando con éxito en el Reino Unido y otros países europeos. En España ha ido ganando terreno en los últimos años y está transformando la manera en que muchos propietarios gestionan —o más bien, dejan de gestionar— sus inmuebles.' },
      { tipo: 'h2', texto: '¿Qué significa exactamente Rent to Rent?' },
      { tipo: 'p', texto: 'Rent to Rent significa, literalmente, alquilar para volver a alquilar. En este modelo, una empresa —el operador RTR— alquila el inmueble al propietario mediante un contrato formal, y luego gestiona ese inmueble alquilando las habitaciones individualmente a distintos residentes.' },
      { tipo: 'p', texto: 'Para el propietario, la experiencia es idéntica a la de un alquiler tradicional, con una diferencia fundamental: su inquilino es una empresa, no un particular.' },
      { tipo: 'h2', texto: '¿Cómo funciona paso a paso?' },
      { tipo: 'ol', items: [
        'El propietario y la empresa RTR firman un contrato de arrendamiento de uso distinto a vivienda',
        'La empresa asume los suministros, el mantenimiento y la gestión integral del inmueble',
        'En muchos casos, la empresa realiza una reforma o acondicionamiento antes de entrar',
        'El propietario cobra su renta puntualmente cada mes, sin intervenir en nada más',
        'Al finalizar el contrato, el inmueble se devuelve en iguales o mejores condiciones',
      ]},
      { tipo: 'h2', texto: '¿Qué ventajas tiene para el propietario?' },
      { tipo: 'h3', texto: 'Renta garantizada sin dependencia del inquilino' },
      { tipo: 'p', texto: 'El propietario cobra su renta aunque el inmueble esté parcialmente vacío o haya problemas con algún residente. Eso es problema del operador RTR, no del propietario. Este es el punto que más valoran los propietarios que han sufrido impagos en el pasado.' },
      { tipo: 'h3', texto: 'Cero gestión' },
      { tipo: 'p', texto: 'Nada de llamadas por averías, nada de negociar con inquilinos, nada de renovar contratos. El propietario tiene un único interlocutor —la empresa— y ese interlocutor se encarga de absolutamente todo.' },
      { tipo: 'h3', texto: 'Inmueble en mejor estado' },
      { tipo: 'p', texto: 'Los operadores RTR profesionales tienen incentivo económico para mantener el inmueble en perfecto estado: un piso bien cuidado se alquila mejor y más rápido. Es habitual que al inicio del contrato se realice una reforma o lavado de cara que mejora el valor del inmueble a largo plazo.' },
      { tipo: 'h3', texto: 'Estabilidad contractual' },
      { tipo: 'p', texto: 'Los contratos de arrendamiento de uso distinto a vivienda tienen una duración más larga que los contratos residenciales estándar. Esto elimina la rotación constante de inquilinos y la incertidumbre asociada.' },
      { tipo: 'h2', texto: '¿Qué dice la ley sobre el Rent to Rent en España?' },
      { tipo: 'p', texto: 'El modelo RTR opera bajo la figura del contrato de arrendamiento de uso distinto a vivienda, regulado por el artículo 3 de la Ley de Arrendamientos Urbanos (LAU). Este tipo de contrato está pensado precisamente para usos que no son exclusivamente residenciales, como los pisos compartidos gestionados profesionalmente.' },
      { tipo: 'p', texto: 'Es un contrato completamente legal, frecuente y bien documentado en la jurisprudencia española. La clave está en que la empresa que firma es el arrendatario y los residentes son sub-arrendatarios o convivientes bajo la responsabilidad del operador, no del propietario.' },
      { tipo: 'destacado', texto: 'En Renttia operamos con contratos de arrendamiento de uso distinto a vivienda revisados por asesoría jurídica. El propietario tiene un único contrato, un único interlocutor y una única transferencia al mes.' },
      { tipo: 'h2', texto: '¿Para qué tipo de propietario funciona mejor el RTR?' },
      { tipo: 'p', texto: 'El modelo RTR es especialmente adecuado para propietarios que tienen un piso de 3 o más habitaciones, que no quieren dedicar tiempo a la gestión y que buscan cobrar su renta de forma fiable cada mes. También es ideal para quienes han tenido malas experiencias con inquilinos en el pasado y buscan una alternativa más segura.' },
    ],
  },
  {
    slug: 'impagos-alquiler-coste-real-propietario',
    categoria: 'Legal y fiscal',
    titulo: 'Impagos en el alquiler: el coste real que muy pocos propietarios calculan',
    extracto: 'Cuando un inquilino deja de pagar, el coste para el propietario va mucho más allá de los meses sin cobrar. Honorarios legales, gastos de comunidad, suministros y el tiempo perdido se acumulan hasta cifras que sorprenden. Analizamos el impacto real.',
    autor: 'Equipo Renttia',
    fecha: '28 jun 2026',
    lectura: '7 min',
    imagen: 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=800&q=80',
    metaDescription: 'Cuánto cuesta realmente un impago de alquiler: meses sin cobrar, honorarios legales, gastos fijos y el coste emocional. Análisis completo para propietarios.',
    contenido: [
      { tipo: 'p', texto: 'El primer mes sin cobrar siempre sorprende. El propietario piensa que será algo puntual, que el inquilino pondrá al día la deuda en pocos días. Pero cuando empieza el proceso de impago, la espiral de costes puede volverse imparable. Este artículo analiza, con números reales, cuánto puede llegar a costar un impago de alquiler en España.' },
      { tipo: 'h2', texto: 'La primera capa de pérdidas: las rentas sin cobrar' },
      { tipo: 'p', texto: 'El caso más habitual es un proceso de desahucio que dura entre 8 y 14 meses. Si la renta es de 800€/mes, el propietario deja de ingresar entre 6.400€ y 11.200€ solo en rentas. Pero eso es solo el principio.' },
      { tipo: 'h2', texto: 'La segunda capa: los gastos que siguen corriendo' },
      { tipo: 'p', texto: 'Aunque el inquilino no pague, el propietario sigue teniendo obligaciones económicas sobre el inmueble. Dependiendo de lo que esté contratado a nombre del propietario:' },
      { tipo: 'ul', items: [
        'Gastos de comunidad: entre 50€ y 150€/mes según el edificio',
        'IBI: proporcional al periodo de impago',
        'Seguro del hogar: si está a nombre del propietario',
        'Hipoteca (si existe): no para ni un solo mes',
      ]},
      { tipo: 'h2', texto: 'La tercera capa: los costes legales' },
      { tipo: 'p', texto: 'Iniciar un proceso de desahucio en España requiere contratar a un abogado y a un procurador. Los costes orientativos son:' },
      { tipo: 'ul', items: [
        'Abogado: entre 800€ y 2.500€ dependiendo de la complejidad y duración',
        'Procurador: entre 200€ y 600€',
        'Tasas judiciales: generalmente exentas para personas físicas, pero existen para empresas',
        'Cerrajero para el lanzamiento: entre 100€ y 300€',
      ]},
      { tipo: 'destacado', texto: 'El coste total de un impago de alquiler en España, incluyendo rentas no cobradas, gastos fijos y costes legales, puede superar los 20.000€ en casos donde el proceso se prolonga más de un año.' },
      { tipo: 'h2', texto: 'El coste que no aparece en ninguna factura: el desgaste emocional' },
      { tipo: 'p', texto: 'La dimensión emocional del impago es real y tiene consecuencias prácticas. Los propietarios que pasan por un proceso de desahucio describen meses de ansiedad, noches sin dormir y una sensación de impotencia ante un sistema que perciben como injusto. Muchos de ellos deciden no volver a alquilar nunca más, perdiendo así la rentabilidad de su inmueble durante años.' },
      { tipo: 'h2', texto: '¿Cómo calcular tu exposición al riesgo?' },
      { tipo: 'p', texto: 'Una fórmula sencilla para estimar tu exposición máxima al riesgo: (Renta mensual × 14) + 3.000€ en gastos legales y administrativos. Ese es el coste que deberías estar dispuesto a asumir antes de alquilar a un particular sin protección adicional.' },
      { tipo: 'h2', texto: 'La alternativa: eliminar el riesgo de raíz' },
      { tipo: 'p', texto: 'La única forma de eliminar completamente el riesgo de impago es que tu inquilino sea una empresa con responsabilidad económica verificable. Cuando una empresa es tu arrendataria, los mecanismos de reclamación son más ágiles y la probabilidad de impago sostenido es estadísticamente mucho menor.' },
      { tipo: 'p', texto: 'Además, una empresa operadora de coliving tiene un incentivo económico directo para mantenerte pagado: si no paga al propietario, pierde el acceso al inmueble y con él toda su actividad. Esa alineación de intereses es la mejor garantía que existe.' },
    ],
  },
  {
    slug: 'contrato-arrendamiento-uso-distinto-vivienda-propietarios',
    categoria: 'Legal y fiscal',
    titulo: 'Contrato de arrendamiento de uso distinto a vivienda: la protección que no sabías que necesitabas',
    extracto: 'El contrato de arrendamiento de uso distinto a vivienda es la figura jurídica que utilizan los operadores de coliving y Rent to Rent en España. Explicamos qué lo diferencia del contrato residencial tradicional y qué ventajas reales ofrece al propietario.',
    autor: 'Equipo Renttia',
    fecha: '20 jun 2026',
    lectura: '6 min',
    imagen: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&q=80',
    metaDescription: 'Qué es el contrato de arrendamiento de uso distinto a vivienda, en qué se diferencia del contrato residencial y por qué protege mejor al propietario que alquila a una empresa.',
    contenido: [
      { tipo: 'p', texto: 'Cuando un propietario firma un contrato de alquiler estándar con un particular, está sujeto a las limitaciones y plazos que establece la Ley de Arrendamientos Urbanos para los contratos de uso de vivienda. Sin embargo, existe otra figura contractual, completamente legal y cada vez más utilizada, que ofrece condiciones más favorables para el propietario: el contrato de arrendamiento de uso distinto a vivienda.' },
      { tipo: 'h2', texto: '¿Qué dice la ley?' },
      { tipo: 'p', texto: 'El artículo 3 de la Ley de Arrendamientos Urbanos (LAU) define el arrendamiento para uso distinto al de vivienda como aquel que recae sobre una edificación habitable cuyo destino primordial sea diferente al de satisfacer la necesidad permanente de vivienda del arrendatario. Este tipo de contrato se rige principalmente por la voluntad de las partes y, supletoriamente, por el Código Civil.' },
      { tipo: 'h2', texto: '¿En qué se diferencia del contrato residencial?' },
      { tipo: 'ul', items: [
        'No hay plazo mínimo obligatorio de 5 años para el propietario como en el contrato residencial',
        'La duración del contrato la pactan libremente las partes',
        'No aplica la prórroga obligatoria de 3 años adicionales del artículo 10 LAU',
        'El proceso de desahucio es más ágil que en el contrato residencial',
        'No existe el derecho de tanteo y retracto del arrendatario en caso de venta',
      ]},
      { tipo: 'h2', texto: '¿Cuándo se utiliza este tipo de contrato?' },
      { tipo: 'p', texto: 'Se utiliza cuando el arrendatario no va a utilizar el inmueble como su residencia habitual y permanente. Es el caso habitual de los operadores de coliving y Rent to Rent: la empresa arrienda el inmueble para gestionarlo como piso compartido, no para vivir en él.' },
      { tipo: 'h3', texto: 'Ejemplos de uso legítimo' },
      { tipo: 'ul', items: [
        'Empresas de coliving que gestionan pisos compartidos profesionalmente',
        'Operadores de alojamiento temporal (estudiantes, trabajadores en movilidad)',
        'Empresas que alquilan pisos para alojar a sus empleados',
        'Inmuebles destinados a uso mixto (residencial y profesional)',
      ]},
      { tipo: 'h2', texto: 'Ventajas concretas para el propietario' },
      { tipo: 'h3', texto: 'Mayor control sobre el inmueble' },
      { tipo: 'p', texto: 'Con un contrato de uso distinto a vivienda, el propietario recupera antes el inmueble si surgen incumplimientos. El proceso judicial es más ágil y predecible que en el desahucio de un contrato residencial.' },
      { tipo: 'h3', texto: 'Condiciones pactadas libremente' },
      { tipo: 'p', texto: 'Desde la duración hasta las condiciones de mantenimiento, reforma o entrega, todo puede pactarse con mayor libertad. Esto permite diseñar un contrato que se adapte exactamente a la situación del inmueble y a las expectativas del propietario.' },
      { tipo: 'destacado', texto: 'En Renttia firmamos siempre contratos de arrendamiento de uso distinto a vivienda, revisados por nuestro asesor jurídico. El propietario recibe una copia completa antes de la firma y dispone del tiempo que necesite para revisarlo con su propio abogado si lo desea.' },
      { tipo: 'h2', texto: '¿Tiene algún riesgo para el propietario?' },
      { tipo: 'p', texto: 'Como todo contrato, debe estar bien redactado y recoger con claridad las obligaciones de ambas partes: qué se entrega, en qué estado, qué puede modificarse en el inmueble, cómo se gestiona el mantenimiento y cómo se resuelve el contrato. Un contrato bien hecho protege a ambas partes y evita conflictos.' },
    ],
  },
  {
    slug: 'como-alquilar-piso-sin-preocupaciones-2026',
    categoria: 'Guías para propietarios',
    titulo: 'Cómo alquilar tu piso sin preocupaciones en 2026: guía práctica para propietarios',
    extracto: 'Alquilar una vivienda en España en 2026 implica más incertidumbre que nunca para los propietarios. En esta guía repasamos las opciones disponibles, sus ventajas e inconvenientes, y los pasos concretos para poner el piso en alquiler de forma segura.',
    autor: 'Equipo Renttia',
    fecha: '10 jun 2026',
    lectura: '10 min',
    imagen: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80',
    metaDescription: 'Guía práctica 2026 para propietarios que quieren alquilar su piso sin riesgos: opciones disponibles, cómo elegir inquilino, qué contratos usar y cómo cobrar siempre.',
    contenido: [
      { tipo: 'p', texto: 'El mercado del alquiler en España atraviesa un momento de alta tensión. La escasez de oferta en ciudades como Zaragoza, Logroño o Huesca convive con un clima de desconfianza entre propietarios que han visto o vivido situaciones de impago, ocupación o conflictos prolongados. Si tienes un piso y te planteas ponerlo en alquiler, esta guía te ayudará a tomar la decisión con información real.' },
      { tipo: 'h2', texto: 'El contexto del alquiler en 2026: qué ha cambiado' },
      { tipo: 'p', texto: 'La Ley de Vivienda de 2023 introdujo cambios relevantes en el mercado del alquiler residencial: limitaciones en zonas tensionadas, modificaciones en los plazos de los contratos y nuevas obligaciones para los grandes tenedores. Para los pequeños propietarios, el impacto más inmediato ha sido un aumento de la incertidumbre jurídica.' },
      { tipo: 'p', texto: 'A esto se suma una percepción generalizada de que el sistema judicial no protege suficientemente al propietario en casos de impago. El resultado: muchos pisos que podrían estar alquilados siguen vacíos porque sus propietarios no quieren arriesgarse.' },
      { tipo: 'h2', texto: 'Opciones para alquilar tu piso: ventajas e inconvenientes' },
      { tipo: 'h3', texto: '1. Alquiler tradicional gestionado por ti mismo' },
      { tipo: 'p', texto: 'Publicas el piso, recibes solicitudes, seleccionas al inquilino, firmas el contrato y gestionas todo lo que surja. Es la opción más común y la que más control da al propietario. También es la que más tiempo y conocimiento requiere, y la que expone más directamente al riesgo de impago.' },
      { tipo: 'h3', texto: '2. Gestión a través de una agencia inmobiliaria' },
      { tipo: 'p', texto: 'La agencia busca inquilino y cobra una comisión (generalmente una mensualidad). Después, la gestión diaria sigue siendo del propietario salvo que contrate un servicio adicional de administración. No elimina el riesgo de impago ni la gestión de incidencias.' },
      { tipo: 'h3', texto: '3. Alquiler con seguro de impago' },
      { tipo: 'p', texto: 'Añadir un seguro de impago (entre el 3% y el 5% de la renta anual) da cobertura durante un máximo de 12 meses y cubre los gastos legales del desahucio. Exige un scoring previo del inquilino. Reduce el riesgo económico pero no elimina el proceso ni el desgaste.' },
      { tipo: 'h3', texto: '4. Alquiler a una empresa (modelo Rent to Rent)' },
      { tipo: 'p', texto: 'El propietario alquila el inmueble a una empresa operadora que se convierte en su único inquilino. La empresa gestiona el inmueble, paga la renta puntualmente y devuelve el inmueble al final del contrato. Es el modelo que más se acerca a "alquilar sin preocupaciones".' },
      { tipo: 'h2', texto: 'Los cinco pasos para alquilar tu piso de forma segura' },
      { tipo: 'ol', items: [
        'Evalúa el estado del inmueble: ¿necesita reforma? ¿está habitable tal como está?',
        'Define tu objetivo: ¿quieres máxima rentabilidad o máxima tranquilidad? Las dos no siempre van juntas',
        'Decide el modelo de alquiler más adecuado para tu perfil y el del inmueble',
        'Prepara la documentación: cédula de habitabilidad, certificado energético, escrituras',
        'Elige bien a quién alquilas: no te precipites por llenar el piso rápido',
      ]},
      { tipo: 'h2', texto: 'Señales de alerta en la selección del inquilino' },
      { tipo: 'p', texto: 'Si optas por el alquiler tradicional, presta atención a estas señales que pueden indicar un perfil de riesgo elevado:' },
      { tipo: 'ul', items: [
        'Urgencia excesiva para firmar el contrato sin tiempo para revisar nada',
        'Nóminas o contratos laborales que no cuadran con el nivel de vida aparente',
        'Resistencia a proporcionar referencias de anteriores arrendadores',
        'Propuestas de pagar varios meses por adelantado sin justificación',
        'Interés en modificar cláusulas estándar del contrato relacionadas con las garantías',
      ]},
      { tipo: 'destacado', texto: 'Si tu piso tiene 3 o más habitaciones y está en Zaragoza, Logroño o Huesca, puedes pedir una valoración gratuita a Renttia. Te diremos si encaja con nuestro modelo y, si es así, te ofrecemos ser nosotros tu inquilino: con contrato, con renta garantizada y sin gestión para ti.' },
      { tipo: 'h2', texto: 'Conclusión: no hay una única respuesta, pero sí hay opciones mejores' },
      { tipo: 'p', texto: 'Alquilar en 2026 es perfectamente viable si se hace con información y con las herramientas adecuadas. El propietario que se protege bien puede obtener una renta estable y predecible de su inmueble durante años, sin sobresaltos. El que se lanza sin preparación asume unos riesgos que pueden costar muy caro.' },
    ],
  },
]
